#!/bin/sh

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

remote="${1}"
url="${2}"

# uncomment to enable
# ===================
#debug=yes
verbose=yes
# ===================

if [ X"${verbose}" = X"yes" ]
then
  printf 'script: %s\n' "${0}"
  printf 'remote: %s @ %s\n' "${remote}" "${url}"
fi


GetYorN() {
  local yorn junk prompt

  prompt="${1}"
  while :
  do
    read -p "${prompt}: [Y/N]? " yorn junk < /dev/tty
    case "${yorn}" in
      ([yY]|[yY][eE][sS])
        return 0
        ;;
      ([nN]|[nN][oO])
        return 1
        ;;
      (*)
        printf 'please answer yes or no\n'
        ;;
    esac
  done
  return 1
}

remote_refs=''

while read local_ref local_sha remote_ref remote_sha
do
  if [ X"${verbose}" = X"yes" ]
  then
    printf 'local_ref: %s [SHA:%s]  remote_ref: %s [SHA:%s]\n' "${local_ref}" "${local_sha}" "${remote_ref}" "${remote_sha}"
  fi
  remote_refs="${remote_refs} ${remote_ref}"
done

[ X"${debug}" = X"yes" ] && set -x


CAPABILITY_URL='cap:one.cap'
CAPABILITY_TARGET='ssh://git@github.com:some-account/some-repo?key=z6MkvRsV39xVQc8HevAQwCqEw18DwrEtzVLz8NJY15NtfMmD'

sign="node --trace-warnings @@JS_DIR@@/sign-invocation.js"
invoke="node --trace-warnings @@JS_DIR@@/invoke.js"

[ X"${verbose}" = X"yes" ] && sign="${sign} -v" && invoke="${invoke} -v"
[ X"${debug}" = X"yes" ] && sign="${sign} -v -v" && invoke="${invoke} -v -v"


rm -f tmp-signed-invocation

cleanup() {
  rm -f tmp-signed-invocation
}
trap cleanup INT EXIT

# simulate secure enclave
sign_invocation() {

  # user: secret key, public key, and did:key from public key
  local USER_SEC='3LftyxxRPxMFXwVChk14HDybE2VnBnPWaLX31WreZwc8V8xCCuoGL7dcyxnwkFXa8D7CZBwAGWj54yqoaxa7gUne'
  local USER_PUB='CXbgG2vPnd8FWLAZHoLRn3s7PRwehWsoMu6v1HhN9brA'
  local USER_DID='did:key:z6MkqyrirHAq8Acicq1FyNJGd9R7D1DW7Q8A3v1qqZfP4pdY'

  ${sign} \
    --capability-url=${CAPABILITY_URL} \
    --target=${CAPABILITY_TARGET} \
    --user=${USER_DID} \
    --user-sec=${USER_SEC} \
    --user-key=0 > tmp-signed-invocation
}

if [ -z "${remote_refs}" ]
then
  printf 'nothing to push\n'
  exit 0
else

  sign_invocation

  if ! ${invoke} < tmp-signed-invocation \
       --target=${CAPABILITY_TARGET} \
       ${remote_refs}
  then
    printf 'push is forbidden\n'
    exit 1
  fi
fi

GetYorN 'manually reject push' && exit 1

exit 0
